### ISSUE TITLE
Error: Tasklist is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Type

### ISSUE THREAD

**Issue by ghost** [ChrisHammond/DNNTemplates#22] opened 2016-05-01 11:48 UTC
hi
i installed dnn 8.0.2 and christoctemplate and works visual 2015
but when debug and check show this error 

please help me

thanks

Error: Tasklist is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Type 'ASP._Page_DesktopModules_MVC_Tasklist_Views__ViewStart_cshtml' does not inherit from 'System.Web.WebPages.StartPage'. ---> System.Web.HttpException: Type 'ASP._Page_DesktopModules_MVC_Tasklist_Views__ViewStart_cshtml' does not inherit from 'System.Web.WebPages.StartPage'. at System.Web.UI.Util.CheckAssignableType(Type baseType, Type type) at System.Web.Compilation.BuildManager.CreateInstanceFromVirtualPath(VirtualPath virtualPath, Type requiredBaseType, HttpContext context, Boolean allowCrossApp) at System.Web.WebPages.BuildManagerWrapper.CreateInstanceOfType[T](String virtualPath) at System.Web.WebPages.VirtualPathFactoryManager.CreateInstanceOfType[T](String virtualPath) at System.Web.WebPages.StartPage.GetStartPage(WebPageRenderingBase page, IVirtualPathFactory virtualPathFactory, String appDomainAppVirtualPath, String fileName, IEnumerable1 supportedExtensions) at System.Web.WebPages.StartPage.GetStartPage(WebPageRenderingBase page, String fileName, IEnumerable1 supportedExtensions) at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) at DotNetNuke.Web.Mvc.Framework.ActionResults.DnnViewResult.ExecuteResult(ControllerContext context, TextWriter writer) at DotNetNuke.Web.Mvc.MvcHostControl.RenderModule(ModuleRequestResult moduleResult) at DotNetNuke.Web.Mvc.MvcHostControl.OnLoad(EventArgs e) --- End of inner exception stack trace ---

**Comment by ChrisHammond** [comment] 2021-02-24 17:46
Closed this issue due to length of time open and lack of reproducability

**Closed as completed** 2021-02-24 17:46 UTC
