### ISSUE TITLE
DNN8 MVC Template Issue

### ISSUE THREAD

**Issue by creatorsoft** [ChrisHammond/DNNTemplates#38] opened 2016-11-01 05:25 UTC
Trying to create an VMC module for DDN8 but getting this error:

---------------------------
Microsoft Visual Studio
---------------------------
Unable to copy the file 'Settings.Designer.cs' from the project template to the project. Cannot find file "C:\Users\AhmadSalem\AppData\Local\Temp\ahgscyrw.vvi\Temp\App_LocalResources\Settings.Designer.cs".

**Comment by ChrisHammond** [comment] 2016-11-02 03:01
What version of the templates are you using?

The reason I ask, this file was JUST added to the solution within the past week, and isn't actually in a released version of the project yet. So either, you downloaded the VSIX I had committed, or you tried to compile the project yourself. Either of which I need to address, but pointing me in the right direction would be helpful.

Thanks

**Comment by creatorsoft** [comment] 2016-11-02 04:43
Thank you for the response. I got the latest from GitHub. Not sure about the version but I am assuming that I have the latest.

**Comment by creatorsoft** [comment] 2016-11-03 22:05
I compiled the project and used the resulting vsix...

**Comment by ChrisHammond** [comment] 2016-11-03 22:43
Try this URL for now please

https://github.com/ChrisHammond/DNNTemplates/raw/master/VSIX/DNNTemplates/bin/Release/DNNTemplates.vsix

**Comment by creatorsoft** [comment] 2016-11-03 23:21
Thank you for the response. I am still getting this error message with the MVC template. The SPA is continuing to work correctly. Thanks...

---

## Microsoft Visual Studio

## Unable to copy the file 'Settings.Designer.cs' from the project template to the project. Cannot find file "C:\Users\AhmadSalem\AppData\Local\Temp\2qgajdnf.asz\Temp\App_LocalResources\Settings.Designer.cs".

## OK

**Comment by ChrisHammond** [comment] 2017-03-08 02:38
At this point I am unable to reproduce this error.

**Closed as completed by ChrisHammond** 2017-03-08 02:38 UTC
