### ISSUE TITLE
Latest version of MSBUILDTASK cause error at compilation 

### ISSUE THREAD

**Issue by vRITHNER** [ChrisHammond/DNNTemplates#40] opened 2017-03-04 10:24 UTC
Hello,
I just installed your template for VS2017.
I create a new module.
I can compile perfectly
In csproj, the end the file:
```
  <PropertyGroup>
    <Extension>zip</Extension>
    <DNNFileName>DNNModuleTest</DNNFileName>
    <PackageName>DNNModuleTest</PackageName>
  </PropertyGroup>
  <Import Project="BuildScripts\ModulePackage.Targets" />
  <Target Name="AfterBuild" DependsOnTargets="PackageModule">
  </Target>
</Project>
```
in package.config, the following line:
`<package id="MSBuildTasks" version="1.5.0.235" targetFramework="net45" developmentDependency="true" />`

Then, I execute the command in package.console:
`update-package MSBuildTasks -reinstall` to force the right target

MSBuildTasks remains the same version but the target is: "net451"
now the package.config contains:
` <package id="MSBuildTasks" version="1.5.0.235" targetFramework="net451" developmentDependency="true" />`

now, the csproj has been modified to become:
```
 <PropertyGroup>
    <Extension>zip</Extension>
    <DNNFileName>DNNModuleTest</DNNFileName>
    <PackageName>DNNModuleTest</PackageName>
  </PropertyGroup>
  <Import Project="BuildScripts\ModulePackage.Targets" />
  <Target Name="AfterBuild" DependsOnTargets="PackageModule">
  </Target>
  <Import Project="..\packages\MSBuildTasks.1.5.0.235\build\MSBuildTasks.targets" Condition="Exists('..\packages\MSBuildTasks.1.5.0.235\build\MSBuildTasks.targets')" />
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\MSBuildTasks.1.5.0.235\build\MSBuildTasks.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MSBuildTasks.1.5.0.235\build\MSBuildTasks.targets'))" />
  </Target>
</Project>
```

When I compile then, I got following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "MSBuild.Community.Tasks.XmlRead" task could not be loaded from the assembly q:\Websites\Modules\CNoteV1\DNNModuleTest\BuildScripts\MSBuild.Community.Tasks.dll. Could not load file or assembly 'file:///q:\Websites\Modules\CNoteV1\DNNModuleTest\BuildScripts\MSBuild.Community.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	DNNModuleTest	
```		
I check the MSBuild.Community.Tasks.Targets file in BuildScript folder and the MSBuildTasks package folder, and there are not identical:

the one from package:
![msbuildtask_01](https://cloud.githubusercontent.com/assets/238842/23577937/d8d90598-00cb-11e7-9003-5b1bdc924597.png)

The one from module project:
![msbuildtask_02](https://cloud.githubusercontent.com/assets/238842/23577940/e37fdf3a-00cb-11e7-953d-540313447bda.png)

The content lines are different too inside the <usingtask, not all files exist in the 2 files.

I tried to copy the one new one inside the project but the error persists.

I spent long hours reading forum articles and trying everything and finally the only way to compile is to remove manually the lines inside the .csproj to revert as the original template.

It could be great in future version of the template to support latest version of dependency nuget package.

Thanks in advance and thanks for your support
-Vince

**Comment by ChrisHammond** [comment] 2017-03-06 04:55
Sorry you ran into the trouble Vince. I've created two skins with this template so far without this issue, not sure why you're experiencing it, but I'll try to recreate the issue and get a fix out

**Comment by vRITHNER** [comment] 2017-03-06 08:43
txs
fyi pbs are not over yet...
Once I fixed the installation, I clicked the view web site button and I got the home page with DNN error.
I changed the output version as debug and I ran it.
It stopped inside the ControlUtilities.cs file (see attached capture).
![dnn_skin_error_01](https://cloud.githubusercontent.com/assets/238842/23602493/1e7b46fc-0251-11e7-8402-f5cdfc5223ae.png)

**Comment by JanOlsmar** [comment] 2017-03-07 10:54
I get the same error as Vince. 
Jan

**Comment by ChrisHammond** [comment] 2017-03-08 02:37
Jan and Vince, what is the problem that you are trying to address by changing the Framework Target?

**Comment by vRITHNER** [comment] 2017-03-08 06:16
Need to develop custom module with 3rd party nugget witch dependencies which require version > 4.5.0

**Comment by linefinc** [comment] 2017-08-27 15:19
I have the same issue with VS2015 and .NET 4.5.2. Switch to 1.4.0.128 and there's no issue.
In the last version, it's missing .build folder

**Comment by JohnTerburg** [comment] 2017-10-16 14:13
Thanks linefinc, this was driving me crazy! On a new PC I had the same problem, whereas on the older machines this wasn't an issue at all. It turns out that if you install 1.5.0.235 some stuff is left out, but if you first revert to 1.4.0.128 on the project(s) the errors go away and then updating from that version to 1.5.0.235 did the trick. On the older systems we kept updating the versions as they came out, so we didn't notice this behaviour.

**Comment by jlojko** [comment] 2017-10-27 01:28
This has helped immensely.  I've been searching for the solution and this information has been extremely helpful.  Can't tell you how much time has been wasted looking for the cause.  Thank you for your efforts and your comments.

**Comment by archer747** [comment] 2018-01-03 18:10
I had the same challenge using Project Templates V9 DNN 7/8/9 for Visual Studio 2017. First, I noticed that the template throws an error while creating the module. Then when I tried to build in Prod mode, it gives the above error. After trying above suggested solutions unsuccessfully, finally got issues with module creation and prod build resolved by running VS as Administrator.

**Closed as completed** 2019-04-04 02:56 UTC
