### ISSUE TITLE
Creates IIS virtual directories

### ISSUE THREAD

**Issue by ralphwilliams** [ChrisHammond/DNNTemplates#10] opened 2015-12-15 20:44 UTC
When doing the initial build, this created virtual directories in IIS for my application in my Desktop Modules folder. I was getting an error when trying to run my site until I removed those virtual directories. Then everything worked splendidly. 

![image](https://cloud.githubusercontent.com/assets/5560203/11823573/ab609456-a342-11e5-8b04-662028e498d6.png)

![image](https://cloud.githubusercontent.com/assets/5560203/11823588/c4a78820-a342-11e5-89d4-80b4cf92c812.png)

**Comment by ChrisHammond** [comment] 2016-01-12 22:37
I have yet to figure out WHY visual studio does this randomly

**Comment by WillStrohl** [comment] 2016-01-12 23:49
Me either.  I've looked into this in the past.  The furthest I got into it had something to do with the IIS settings in the .proj file, but I wasn't able to isolate why/how.

**Comment by INNO-Software** [comment] 2016-01-29 07:13
It happened to me while I was adjusting the project's settings for a web server. Specifically I was toggling between IIS and IIS Express and adjusting the start-up URL, etc. When it prompted me to create a virtual directory I actually said NO. Then when the site started throwing errors I realized it had still triggered. 

Not sure if it is a coincidence but it seems related. Even if it just triggers something else that actually causes it.

As with everyone else, I just remove them manually. More annoying than anything.

**Comment by VashJuan** [comment] 2019-05-05 01:16
Happened to me too. Thanks for the solution!

**Comment by ChrisHammond** [comment] 2021-02-24 17:40
Closing as I simply haven't found the cause for this.

**Closed as completed by ChrisHammond** 2021-02-24 17:40 UTC
